language: rust
cache:
  cargo: true
rust:
  - stable
  - beta
before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt --all -- --check
  - cargo clippy --all --all-targets --all-features -- -D warnings
  - cargo test --all --all-features
  - cargo doc --no-deps --document-private-items --all
