[package]
name = "predicate-plugins"
version = "0.1.0"
authors = ["Cryptoeconomics Lab <info@cryptoeconomicslab.com>"]
edition = "2018"

[dependencies]
ethabi = "7.0.0"
ethereum-types = "^0.5.2"
plasma-core = { path = "../core" }
