[package]
name = "plasma-operator"
version = "0.1.0"
authors = ["Cryptoeconomics Lab <info@cryptoeconomicslab.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.1"
plasma-core = { path = "../core" }
jsonrpc-http-server = "11.0.0"
log = "0.4.6"
